[book]
authors = ["Jaime Barillas"]
language = "en"
src = "src"
title = "Demo"

# ANCHOR: output-html-header
[output.html]
# ANCHOR_END: output-html-header

# ANCHOR: output-html-required
additional-css = ["mdbook-theme/mdbook-theme.css"]
additional-js = ["mdbook-theme/mdbook-theme.js"]
# ANCHOR_END: output-html-required

# ANCHOR: output-html-recommended
no-section-label = true
# ANCHOR_END: output-html-recommended

# ANCHOR: recommended-config-changes
[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 1
# ANCHOR_END: recommended-config-changes
