#!/usr/bin/env bash
set -euxo pipefail

#### Generate both the server's and client's private key and self-signed SSL
#### cert.
#### Commands follow those generated by https://certificatetools.com.

# TODO: ensure file pertmissions and owner is correctly set

cd cert/

## Server
## Generate the server RSA private key.
openssl genpkey -outform PEM -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out server.key # -outpubkey server.pub

## Generate the server certificate signing request.
openssl req -new -nodes -key server.key -config server-csrconfig.txt -nameopt utf8 -utf8 -out server-cert.csr

## Self sign the server CSR, generating the cert.
openssl req -x509 -nodes -in server-cert.csr -days 365 -key server.key -config server-certconfig.txt -extensions req_ext -nameopt utf8 -utf8 -out server-cert.crt

## Client
## Generate the client RSA private key
openssl genpkey -outform PEM -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out client.key

## Generate the client certificate signing request.
openssl req -new -nodes -key client.key -config client-csrconfig.txt -nameopt utf8 -utf8 -out client-cert.csr

## Self sign the client CSR, generating the cert.
openssl req -x509 -nodes -in client-cert.csr -days 365 -key client.key -config client-certconfig.txt -extensions req_ext -nameopt utf8 -utf8 -out client-cert.crt
